name = "SmallCouplingDynamicCavity"
uuid = "1607259e-80f4-4675-b495-cb9c54bacb3f"
authors = ["Mattia tarabolo <mattia.tarabolo@gmail.com>"]
version = "1.0.1"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
Distributions = "0.25"
Graphs = "1"
julia = "1"
SparseArrays = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
