name = "SmallCouplingDynamicCavity"
uuid = "1607259e-80f4-4675-b495-cb9c54bacb3f"
authors = ["Mattia tarabolo <mattia.tarabolo@gmail.com>"]
version = "3.0.1"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
Distributions = "0.25"
Graphs = "1"
SparseArrays = "1"
StatsBase = "0.34.2"
julia = "1.9"
